const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#000',
    background: '#fff',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    // Game UI tokens
    screenBackground: '#F0F4FF',
    cardBackground: '#FFFFFF',
    cardBorder: '#D0DCFF',
    cardShadow: '#B8CAFF',
    accent: '#4A6FE3',
    accentDark: '#3557C8',
    accentText: '#FFFFFF',
    startButton: '#F5A623',
    startButtonDark: '#D48C10',
    starActive: '#F5A623',
    starInactive: '#D0DCFF',
    arrowButton: '#4A6FE3',
    arrowButtonDisabled: '#D0DCFF',
    levelLabel: '#1A2A6C',
    levelDescription: '#5C6BC0',
  },
  dark: {
    text: '#fff',
    background: '#000',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    // Game UI tokens
    screenBackground: '#0D1128',
    cardBackground: '#1A2340',
    cardBorder: '#2E3F7F',
    cardShadow: '#0A0F1E',
    accent: '#6B8EFF',
    accentDark: '#4A6FE3',
    accentText: '#FFFFFF',
    startButton: '#F5A623',
    startButtonDark: '#D48C10',
    starActive: '#F5A623',
    starInactive: '#2E3F7F',
    arrowButton: '#6B8EFF',
    arrowButtonDisabled: '#2E3F7F',
    levelLabel: '#C5D0FF',
    levelDescription: '#8FA0E0',
  },
};
